"""Initial migration.

Revision ID: 13582e6274a6
Revises: 
Create Date: 2024-01-10 13:38:49.554557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13582e6274a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('publisher', sa.String(length=100), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('Copies' , sa.Integer(), nullable=False),
    sa.Column('rented' , sa.Integer(), nullable = False),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rent',
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('borrowed_quantity', sa.Integer(), nullable=True),
    sa.Column('stu_id' , sa.Integer() , nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20),default='pending'),


    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['stu_id'], ['student.id'], ),

    sa.PrimaryKeyConstraint('rid')
    )
    op.create_table('fee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stu_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('rent_fee', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['stu_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('stock')
    op.drop_table('member')
    op.drop_table('charges')
    op.drop_table('book')
